apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app.kubernetes.io/name: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: 601755645937.dkr.ecr.ap-southeast-1.amazonaws.com/simplebank:0f3ca69cc712f01b1ccc6205d083614dbd37b13f
          ports:
            - containerPort: 8080
